name: test
on: push
permissions:
  contents: read
  security-events: write

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Run Ansible scan with SARIF output
        uses: xlab-steampunk/spotter-action@master
        env:
          SPOTTER_API_TOKEN: ${{ secrets.SPOTTER_TOKEN }}
        with:
          ansible_version: 2.16
#          profile: gitlab
          project_id: ${{ secrets.SPOTTER_PROJECT }}
          sarif_file: example.sarif
        continue-on-error: true

      - name: Rename SARIF tool to force all alerts
        run: |
          TIMESTAMP=$(date +%s)
          TOOL_NAME="spotter-custom-${TIMESTAMP}"
          jq ".runs[].tool.driver.name = \"${TOOL_NAME}\"" example.sarif > example-updated.sarif
        shell: bash

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: example-updated.sarif
          category: force-all-${{ github.run_id }}
